[package]
name = "Guulveig_Diet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive","color"] }
toml = "0.5.8"
serde = "1.0"
serde_derive = "1.0"
csv = "1.1"